CREATE TABLE[dbo].[TB_USUARIO] (
[I_COD_USUARIO]	INT IDENTITY(1, 1) NOT NULL,
[S_NM_USUARIO] VARCHAR(35) NOT NULL,
[S_SN_USUARIO] VARCHAR(33) NOT NULL,
PRIMARY KEY CLUSTERED ([I_COD_USUARIO] ASC)
);
GO
CREATE TABLE[dbo].[TB_TURMA] (
[I_COD_TURMA] INT IDENTITY(1, 1) NOT NULL,
[I_ANO_TURMA] INT NOT NULL,
[S_LETRA_TURMA] VARCHAR(1) NOT NULL,
PRIMARY KEY CLUSTERED ([I_COD_TURMA] ASC)
);
GO
CREATE TABLE[dbo].[TB_ALUNO] (
[I_COD_ALUNO]	INT IDENTITY(1, 1) NOT NULL,
[I_COD_TURMA] INT NOT NULL,
[S_NM_ALUNO] VARCHAR(35) NOT NULL,
[I_NMR_ALUNO] INT NOT NULL,
PRIMARY KEY CLUSTERED ([I_COD_ALUNO] ASC),
FOREIGN KEY ([I_COD_TURMA]) REFERENCES [dbo].[TB_TURMA] ([I_COD_TURMA])
);
GO
CREATE TABLE[dbo].[TB_PARTIDA] (
[I_COD_BIMESTRE]  INT IDENTITY(1, 1) NOT NULL,
[I_ANO_LET_BIMESTRE] INT NOT NULL,
[I_BIMESTRE] INT NOT NULL,
PRIMARY KEY CLUSTERED ([I_COD_BIMESTRE] ASC),
);
GO
CREATE TABLE[dbo].[TB_MEDIAS] (
[I_COD_MEDIAS] INT IDENTITY(1, 1) NOT NULL,
[I_COD_ALUNO] INT NOT NULL,
[I_COD_BIMESTRE]  INT NOT NULL,
[D_MPOR_MEDIAS]  DECIMAL(2,1) NOT NULL,
[D_MMAT_MEDIAS]  DECIMAL(2,1) NOT NULL,
[D_MQUI_MEDIAS]  DECIMAL(2,1) NOT NULL,
[D_MFIS_MEDIAS]  DECIMAL(2,1) NOT NULL,
[D_MBIO_MEDIAS]  DECIMAL(2,1) NOT NULL,
[D_MART_MEDIAS]  DECIMAL(2,1) NOT NULL,
[D_MHIS_MEDIAS]  DECIMAL(2,1) NOT NULL,
[D_MEDFIS_MEDIAS]  DECIMAL(2,1) NOT NULL,
[D_MING_MEDIAS]  DECIMAL(2,1) NOT NULL,
[D_MGEO_MEDIAS]  DECIMAL(2,1) NOT NULL,
[D_MSOC_MEDIAS]  DECIMAL(2,1) NOT NULL,
PRIMARY KEY CLUSTERED ([I_COD_MEDIAS] ASC),
FOREIGN KEY ([I_COD_ALUNO]) REFERENCES [dbo].[TB_ALUNO] ([I_COD_PARTIDA]),
FOREIGN KEY ([I_COD_BIMESTRE]) REFERENCES [dbo].[TB_BIMESTRE] ([I_COD_BIMESTRE])
);
